name: Deploy

env:
  GH_REF: ${{ github.event.inputs.ref }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'a specific branch, commit or tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GH_REF }}